# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 13:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180214_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='TallySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('version_number', models.IntegerField(default=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='authevent',
            name='has_ballot_boxes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.CharField(choices=[('authevent:create', 'authevent:create'), ('authevent:callback', 'authevent:callback'), ('authevent:edit', 'authevent:edit'), ('authevent:start', 'authevent:start'), ('authevent:stop', 'authevent:stop'), ('user:activate', 'user:activate'), ('user:successful-login', 'user:successful-login'), ('user:send-auth', 'user:send-auth'), ('user:deactivate', 'user:deactivate'), ('user:register', 'user:register'), ('user:added-to-census', 'user:added-to-census'), ('user:resend-authcode', 'user:resend-authcode')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='action',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tallysheet',
            name='ballot_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_sheets', to='api.BallotBox'),
        ),
        migrations.AddField(
            model_name='ballotbox',
            name='auth_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballot_boxes', to='api.AuthEvent'),
        ),
        migrations.AlterUniqueTogether(
            name='ballotbox',
            unique_together=set([('auth_event', 'name')]),
        ),
    ]
