# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-18 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0036_auto_20180314_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallysheet',
            name='creator',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='created_tally_sheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
