# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-29 09:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20180329_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.CharField(choices=[('authevent:create', 'authevent:create'), ('authevent:callback', 'authevent:callback'), ('authevent:edit', 'authevent:edit'), ('authevent:start', 'authevent:start'), ('authevent:stop', 'authevent:stop'), ('user:activate', 'user:activate'), ('user:successful-login', 'user:successful-login'), ('user:send-auth', 'user:send-auth'), ('user:deactivate', 'user:deactivate'), ('user:register', 'user:register'), ('user:added-to-census', 'user:added-to-census'), ('user:deleted-from-census', 'user:deleted-from-census'), ('user:resend-authcode', 'user:resend-authcode')], db_index=True, max_length=255),
        ),
    ]

