# Generated by Django 2.2.10 on 2020-03-03 22:53

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_hide_default_login_lookup_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='authevent',
            name='children_election_info',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authevent',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.AuthEvent'),
        ),
    ]
