# Generated by Django 2.2.10 on 2020-03-04 15:13

import api.models
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20200303_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='children_event_id_list',
            field=jsonfield.fields.JSONField(blank=True, null=True, validators=[api.models.children_event_id_list_validator]),
        ),
        migrations.AlterField(
            model_name='authevent',
            name='children_election_info',
            field=jsonfield.fields.JSONField(blank=True, null=True, validators=[api.models.children_election_info_validator]),
        ),
    ]
