# Generated by Edulix on 2022-10-19 10:00

from django.db import models, migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_authevent_allowed_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='authevent',
            name='support_otl_enabled',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authevent',
            name='inside_authenticate_otl_period',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
