# Generated by Edulix on 2023-04-27 10:10

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0049_authevent_add_otl'),
    ]

    operations = [
        migrations.AddField(
            model_name='authevent',
            name='tally_mode',
            field=models.CharField(
                default='active',
                max_length=15,
                choices=[
                    ('active', 'active'),
                    ('all', 'all'),
                ]
            ),
            preserve_default=False
        )
    ]
