# Generated by Edulix on 2023-07-12 16:40

from django.db import migrations, models
from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0051_authevent_alternative_auth_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='authevent',
            name='scheduled_events',
            field=JSONField(blank=True, db_index=False, null=True),
            preserve_default=False
        )
    ]
