# Generated by Edulix on 2023-11-10 08:16

from django.db import migrations, models
from django.contrib.postgres.fields import JSONField

class Migration(migrations.Migration):
    dependencies = [
        ('api', '0052_authapi_scheduled_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='authevent',
            name='oidc_providers',
            field=JSONField(blank=True, db_index=False, null=True),
            preserve_default=False
        )
    ]
