---
resolutions:
  rule_violations:
  - message: "The package PyPI::.* has the declared ScanCode copyleft.limited categorized license LGPL.*"
    reason: "DYNAMIC_LINKAGE_EXCEPTION"
    comment: "This is not a problem because python modules are always dynamic, see https://stackoverflow.com/questions/8580223/using-python-module-on-lgpl-license-in-commercial-product and https://mail.python.org/pipermail/tutor/2015-June/105759.html."
  - message: "The package PyPI::.* has the declared ScanCode copyleft-limited categorized license MPL.*"
    reason: "DYNAMIC_LINKAGE_EXCEPTION"
    comment: "This is not a problem because we are not modifying the MPL code."
