language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
# command to run tests
script:
  - cd authapi
  - python manage.py migrate --settings=authapi.test_settings
  - python manage.py loaddata --settings=authapi.test_settings initial
  - python manage.py test --settings=authapi.test_settings
  - coverage run --source='.' manage.py test --settings=authapi.test_settings
after_success: coveralls
