language: python
python:
  - "3.5"
addons:
  postgresql: "9.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
services:
  - postgresql
# command to run tests
before_script:
  - psql -tAc "CREATE USER authapi WITH PASSWORD '<PASSWORD>';" -U postgres
  - psql -tAc "ALTER USER authapi CREATEDB;" -U postgres
  - psql -tAc "CREATE DATABASE authapi OWNER authapi;" -U postgres
script:
  - cd authapi
  - python manage.py migrate --settings=authapi.test_settings
  - python manage.py loaddata --settings=authapi.test_settings initial
  - python manage.py test --settings=authapi.test_settings
  - coverage run --source='.' manage.py test --settings=authapi.test_settings
after_success: coveralls
