# Generated by Edulix on 2021-11-12 13:00

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('authmethods', '0008_auto_20150417_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='Code',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
