# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 13:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_admin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='admin_fields',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_index=True, default={}, null=True),
        ),
    ]
