# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-25 21:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='draft_election',
            field=jsonfield.fields.JSONField(blank=True, db_index=False, default=[], null=True),
        ),
    ] 
