# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-14 09:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.CharField(choices=[('authevent:create', 'authevent:create'), ('authevent:callback', 'authevent:callback'), ('authevent:edit', 'authevent:edit'), ('authevent:start', 'authevent:start'), ('authevent:stop', 'authevent:stop'), ('authevent:delete', 'authevent:delete'), ('user:activate', 'user:activate'), ('user:successful-login', 'user:successful-login'), ('user:send-auth', 'user:send-auth'), ('user:deactivate', 'user:deactivate'), ('user:register', 'user:register'), ('user:resend-authcode', 'user:resend-authcode')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='action',
            name='executer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
