# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-14 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20180311_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ballotbox',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='tallysheet',
            name='version_number',
        ),
    ]
