# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 16:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_tallysheet_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, db_index=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, db_index=True),
        ),
    ]
