# Generated by Django 2.0.13 on 2020-01-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20190129_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_name',
            field=models.CharField(choices=[('authevent:create', 'authevent:create'), ('authevent:callback', 'authevent:callback'), ('authevent:edit', 'authevent:edit'), ('authevent:start', 'authevent:start'), ('authevent:stop', 'authevent:stop'), ('user:activate', 'user:activate'), ('user:successful-login', 'user:successful-login'), ('user:send-auth', 'user:send-auth'), ('user:deactivate', 'user:deactivate'), ('user:register', 'user:register'), ('user:authenticate', 'user:authenticate'), ('user:added-to-census', 'user:added-to-census'), ('user:deleted-from-census', 'user:deleted-from-census'), ('user:resend-authcode', 'user:resend-authcode')], db_index=True, max_length=255),
        ),
    ]
