# -*- coding: utf-8 -*-
# Generated by Edulix manually on 2020-03-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20200125_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='authevent',
            name='hide_default_login_lookup_field',
            field=models.BooleanField(default=False),
        ),
    ]
