# Generated by Django 2.2.10 on 2020-03-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20200304_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfullogin',
            name='auth_event',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='successful_logins', to='api.AuthEvent'),
        ),
    ]
