# Generated by Django 2.2.10 on 2020-03-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_successfullogin_auth_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='authevent',
            name='tally_status',
            field=models.CharField(choices=[('notstarted', 'notstarted'), ('pending', 'pending'), ('started', 'started'), ('success', 'success')], default='notstarted', max_length=15),
        ),
    ]
