# Generated by Edulix on 2021-09-30 13:20

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_userdata_tally_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='use_generated_auth_code',
            field=models.BooleanField(default=False),
        ),
    ]
