# Generated by Django 2.2.25 on 2022-01-16 11:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0048_authevent_allowed_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id', 
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'created'),
                            ('pending', 'pending'),
                            ('running', 'running'),
                            ('success', 'success'),
                            ('error', 'error')
                        ],
                        db_index=True,
                        max_length=255
                    )
                ),
                (
                    'metadata',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        db_index=True,
                        default=dict
                    )
                ),
                (
                    'name',
                    models.CharField(db_index=True, max_length=255)
                ),
                (
                    'input',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    )
                ),
                (
                    'output',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    )
                ),
                (
                    'executer',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE, related_name='executed_tasks',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
        ),
    ]
