# This file is part of authapi.
# Copyright (C) 2022 Sequent Tech Inc <legal@sequentech.io>

# authapi is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License.

# authapi  is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with authapi.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 2.2.25 on 2022-01-16 11:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id', 
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('created', 'created'),
                            ('pending', 'pending'),
                            ('running', 'running'),
                            ('success', 'success'),
                            ('cancelling', 'cancelling'),
                            ('cancelled', 'cancelled'),
                            ('error', 'error')
                        ],
                        db_index=True,
                        max_length=255
                    )
                ),
                (
                    'metadata',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        db_index=True,
                        default=dict
                    )
                ),
                (
                    'name',
                    models.CharField(db_index=True, max_length=255)
                ),
                (
                    'input',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    )
                ),
                (
                    'output',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict
                    )
                ),
                (
                    'executer',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE, related_name='executed_tasks',
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],
        ),
    ]
