# SPDX-FileCopyrightText: 2014-2021 Sequent Tech Inc <legal@sequentech.io>
#
# SPDX-License-Identifier: AGPL-3.0-only
name: ORT licensing

on:
  push:
    branches:
    - master
    - '[0-9]+.[0-9]+.x'
    tags:
    - '**'
  pull_request:
    branches:
    - master
    - '[0-9]+.[0-9]+.x'

jobs:
  ort:
    runs-on: ubuntu-20.04
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/

      - uses: actions/checkout@v2

      #- name: Analyze licensing
      #  id: ort-action
      #  uses: edulix/ort-action@develop
      #  with:
      #    package-curations-dir: .ort-data/curations-dir/
      #    rules-file: .ort-data/rules.kts
      #    license-classifications-file: .ort-data/license-classifications.yml
      #    reporters: AdocTemplate,PdfTemplate,Excel,StaticHtml,WebApp
      #    ort-extra-args: -P ort.severeRuleViolationThreshold=HINT --debug
      #    report-extra-args: >
      #      --report-option
      #      PdfTemplate=template.path=/project/.ort-data/disclosure_document.ftl

      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@main
        with:
          log-level: debug
          # advisors: '' # don't run advisors, we use github for that
          #fail-on: issues,violations
          report-formats: SpdxDocument,Excel,StaticHtml,WebApp
          ort-cli-args: > # using the default plus the package managers setting
            --force-overwrite
            --stacktrace
            -P ort.analyzer.enabledPackageManagers=PIP
          ort-cli-evaluate-args: >
            --rules-file ${{ github.workspace }}/.ort-data/rules.kts
            --license-classifications-file ${{ github.workspace }}/.ort-data/license-classifications.yml
